### ISSUE TITLE
Carrot Appearance

### ISSUE THREAD

**Issue by R3ngad33** [R3ngad33/UOS#2]
The carrot that is used in game is attached for example:
![carrot](https://user-images.githubusercontent.com/35588970/35185869-b64ef6b2-fdd8-11e7-9cb7-e863da2159f8.png)

it may be best to draw a rectangle or perhaps use the alt codes 221 or 222 ( ▌▐ )

**Comment by Windspar** [comment]
Did the new cursor fix this for you ?

**Comment by R3ngad33** [comment]
Yes it is perfect
